version: "3.8"
services: 
    # mongo:
    #     image: mongo
    #     restart: on-failure
    #     environment: 
    #         - MONGO_INITDB_DATABASE=vinylhunt
    #         - MONGO_INITDB_ROOT_USERNAME=mongo
    #         - MONGO_INITDB_ROOT_PASSWORD=password
    #     ports: 
    #         - "27017-27019:27017-27019"
    #     volumes: 
    #         - .mongodata:/data/db 
    web:
        container_name: node-server
        image: node
        volumes:
            - .:/usr/src/app
        working_dir: /usr/src/app
        # depends_on:
        #     - mongo
        restart: on-failure
        command: "npm run build-prod"
        ports: 
            - "3000:3000"